import type { Metadata } from 'next'
import '../src/app/styles/globals.css'

export const metadata: Metadata = {
	title: 'Gosha',
	description: 'Generated by create next app',
}

export const viewport = {
	width: 'device-width',
	initialScale: 1,
	maximumScale: 1,
	userScalable: false,
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body>{children}</body>
		</html>
	)
}
